### PR TITLE
Fix clang-format version to between v13 and v15

### PR DESCRIPTION
**Pull request by valassi**
Fix clang-format version to v15 see #952

### CODE REVIEW

**Comment by valassi** [comment]
Hi @oliviermattelaer I'd like to merge this, just to have fewer PRs up in the air.

This should be totslly non controversial, only changes a script that I use in generateAndCompare. It needs to use clang format not higher than v15, else all formatting will change.

Let me know if you have comments please, but I might merge anyway.

**Comment by valassi** [comment]
Note: I could not test this fully on itgold91 because of https://github.com/mg5amcnlo/mg5amcnlo/issues/127

**Comment by oliviermattelaer** [comment]
no objection.

**Comment by valassi** [comment]
> no objection.

Thanks :-)

Merging

**Pull request merged**
