### PR TITLE
Fix 825

### LINKED ISSUE #825: Cross section mismatch (fortran/cpp) in SUSY gg_tt
Cross section mismatch (fortran/cpp) in SUSY gg_tt

In PR #824 I fixed SUSY codegen, builds and internal tests cuda/cpp.
But now I ALSO added the test comparing to fortran and this fails

In tmad/logs_susyggtt_mad/log_susyggtt_mad_d_inl0_hrd0.txt
```
ERROR! xsec from fortran (44.598860065419856) and cpp (171.81273026311101) differ by more than 3E-14 (2.85240183294
1188)
```

### PR DESCRIPTION
**Pull request by oliviermattelaer**
This does fix #825 where the problem was that the unary handling was not propagated within the aloha routine.
This patch include such handling now but I'm a bit worried about other processes that can be impacted.
This PR (via the CI) is a simple way to test many processes to spot potential issue, if it goes trough, I will anyway have to check the corner case, I'm worried about...

### CODE REVIEW

**Comment by oliviermattelaer** [comment]
@roiser, ok this is good to be squashed and merged.

Olivier

**Comment by valassi** [comment]
Hi @oliviermattelaer I had a look since I saw that you posted this.

I confirm that #825 seems fixed: the cross section from fortran and cuda/c++ now matches in susy_gg_tt. 

Conversely for #826 I still see that there is NO cross section for susy_gg_t1t1. So I am a bit surprised when you say that you do see a cross section. Maybe it depends on the number of events and the exact setup? Anyway, I agree with you that this needs more investigation.

One point, I see that this patch also changes the Parameters.h files in other processes including eemumu. Is this expected? Anyway, I will run a few tests on all processes and see what this gives.

Just in case, this is in https://github.com/valassi/madgraph4gpu/tree/susy (but I will not make a PR out of this, at least not yet)

Thanks! Andrea

**Comment by oliviermattelaer** [comment]
Hi Andrea,

in Parameters.h  this sounds surprising (I do not see any of those files changed in your repo actually)
But in all process/model, the file HelAmps_sm.h is going to be modified since the issue has nothing specific to the MSSM model and we could --maybe we should--  have detected in the SM has well.

For #826, I will "first" try to fix the missmatch that I do observe on my laptop, and then we might need to work together to understand why your machine is just crashing (if it is still happens at that stage obviously).

**Comment by valassi** [comment]
> Hi Andrea,
> 
> in Parameters.h this sounds surprising 

OPS! SORRY! Yes I meant that HelAmps.h changed, not Paramaters.h!

**Comment by valassi** [comment]
For me this is good to go and should be merged. However it will then also need an update of refence files for runTest (#859), which is in my PR #860. So I suggest, 
- either merge this #850 first and then my #860
- or merge directly my #860 which includes this #850
The result should be the same. Thanks

**Comment by valassi** [comment]
I merged my #860. As I expected, github automatically closed this one as merged too. Thanks Olivier!

**Pull request merged**
