### PR TITLE
workaround for FPE in vxxxxx on HIP (and fixes for v1.00.01 tags)

### PR DESCRIPTION
**Pull request by valassi**
This is a WIP PR with a workaround for FPE in vxxxxx on HIP #1011

It is WIP because
- must first release 1.00.00 and merge #1008 
- must backport to codegen, regenerate code, run all tests

### CODE REVIEW

**Comment by valassi** [comment]
> * must first release 1.00.00

this is done, I have resynced this to the latest master

I also fixed #1013 an dincluded this here

> * must backport to codegen, regenerate code, run all tests

codegen backported, I regenerated all processes

I will run all tests later on

**Comment by valassi** [comment]
Hi @oliviermattelaer this is also ready for merging, it fixes some FPEs on HIP GPUs

(And it includes #1014)

Can you approve please? Thanks Andrea

**Review by oliviermattelaer — APPROVED** [review]
perfect thanks

**Comment by valassi** [comment]
Very good @oliviermattelaer thanks!
Merging now
Andrea

**Pull request merged**
