### PR TITLE
WIP - extract gpu properties

### PR DESCRIPTION
**Pull request by roiser**
little tool to extract gpu card properties

### CODE REVIEW

**Comment by lfield** [comment]
Have you tried the clinfo command?

**Comment by roiser** [comment]
No I didn't know the tool. I just compiled it from source ( https://github.com/Oblomov/clinfo ) and it delivers the same info (even a bit more) than the script. 

Do you know if there is an rpm for e.g. Centos8? I couldn't find one. Also we would introduce a dependency on OpenCL, I'm a bit wary if we want to do this.

Just to add. In view of upcoming testing I thought it may be useful to extract necessary info about the underlying card to allow us to configure the performance tests accordingly.

**Comment by lfield** [comment]
There isn't a one to one mapping for the properties but it does give a similar overview. I had the same idea as you when I was looking at the OpenCL API but then found this instead. It does't add many dependencies. All GPU/FPGA cards should support a version of OpenCL and the OpenCL lib is readily available. The package is not in EPEL for CentOS8 but I can ask the packager if they can release it. There are also two SYCL info versions but I haven't tied them yet. Might do that today.

**Comment by lfield** [comment]
There is also glxinfo for the OpenGL API. Rather than gpuprops I would call this CUDA info but I would be surprised if this tool did not already exist.

**Comment by lfield** [comment]
btw WIP pull requests should be opened as draft pull requests.

**Comment by roiser** [comment]
> btw WIP pull requests should be opened as draft pull requests.

thanks, converted now, the reason why it was a "normal" PR is that I"m using by default the URL that git provides to me after pushing which seems to make it a standard PR

**Comment by lfield** [comment]
Have you tried this in the samples directory?

/usr/local/cuda/samples/1_Utilities/deviceQuery

**Comment by lfield** [comment]
In fact building and running deviceQuery is a [recommend action](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#running-binaries) for verifying the integrity of the installation.

**Pull request merged**
