### PR TITLE
Test and complete the fix for 825 in PR 850

### PR DESCRIPTION
**Pull request by valassi**
Hi @oliviermattelaer this is a PR where I test and complete your fix in PR #850 for #825 (xsec mismatch in susy_gg_tt).

Your patch is good and we should merge it. In these tests however I found that a few additions are needed, in particular the reference files for runTest.exe must be updated (the code changed after adding Ccoeff, so I would say that the old reference files were wrong, see #859).

Still in WIP for now but will be ready soon.

### CODE REVIEW

**Comment by valassi** [comment]
Note: after fixing #825 with PR #850, again a SIGFPE reappeared also in gqttq. This is what I had reported in #845. I think that most likely this is the same SIGFPE crash in rotxxx #855 and can be fixed by adding volatile in PR #857... but I will check that.

**Comment by valassi** [comment]
Hi Olivier, this is now also ready for merging.It includes your #850 and complements it with an update of the susy reference files for runTest (#859), plus various other tests. Can you please have a look and approve?

I would suggest to first merge your #850 and then this one. Or I think that one can merge this directly and it will automatically close your #850 as merged.

Reminder, there are two other PRs from me ready to be reviewed and merged: PR #854 (just adding matrix.pdf files for easier visualization than ps) and PR #857 (fixing the SIGFPE crash in rotxxx by adding volatile).

Instead, I think that issues #826 (no xsec in susy_gg_t1t1) and #845 (SIGFPE crash in gqttq) are still pedning to be debugged. I think that a combination of your PR #852 and my PR #853 might fix those, but as far as I am concerned this will wait for end June.

Thanks!
Andrea

**Review by oliviermattelaer — APPROVED** [review]
Thanks Andrea, yes this can be merged.
(and no need to merge my PR first)

Cheers,

Olivier

**Comment by valassi** [comment]
Thanks Olivier, merging now

**Pull request merged**
