### PR TITLE
Additional fixes/tests over Olivier's master_for360

### PR DESCRIPTION
**Pull request by valassi**
This is a WIP PR with additional fixes/tests over @oliviermattelaer 's master_for360 in #992.

The work by Olivier was already so good/complete that there may be almost nothing to do in addition.

Here I have just regenerated all processes, so that I can launch my manual tests and the CI.

Tomorrow I will have a more detailed look.

### CODE REVIEW

**Comment by valassi** [comment]
All checks have passed in the CI against master
image

I will now change this to target Olivier's master_for360 instead

**Comment by valassi** [comment]
Hi @oliviermattelaer this is ready for review.

I changed the base to be your master_for360. So I suggest that we merge the whole chain
1. First we merge https://github.com/mg5amcnlo/mg5amcnlo/pull/140 into gpucpp in th emg5amcnlo repo (I approved the PR)
2. Then (or before 1, whatever) we merge this https://github.com/madgraph5/madgraph4gpu/pull/997 into your master_for360
3. Finally (after the above two) we merge your https://github.com/madgraph5/madgraph4gpu/pull/992 into master

Can I go ahead with merging this one into your master_v360?

**Comment by valassi** [comment]
NB Just to document this: in addition to #992, this ONLY does the following
- regenerate all processes in the madgraph4gpu repo
- rerun some tests 
- it does NOT change CODEGEN or mg5amc

**Review by oliviermattelaer — APPROVED** [review]
Perfect, this can be merge as soon as you want

**Comment by valassi** [comment]
Thanks Olivier! Merging now

**Pull request merged**
