### PR TITLE
Disable hipcc optimizations i.e. use -O2 instead of -O3 (work around for gq_ttq crash 806 on AMD GPUs at LUMI)

### PR DESCRIPTION
**Pull request by valassi**
Disable hipcc optimizations i.e. use -O0 instead of -O3 (work around for gq_ttq crash #806)

### CODE REVIEW

**Comment by valassi** [comment]
I actually checked that -O2 is still ok, so I moved to that instead of -O0, this will be better for performance.

But -O3 gives crashes, to be investigated in #806

**Comment by valassi** [comment]
Hi @oliviermattelaer can you please review?

The ONLY change is that OPTFLAGS=-O2 is used instead of -O3 and ONLY for hip on AMD GPUs.

Plus all processes are regenerated, and my usual tests will appear tomorrow after I run them.

Thanks!

**Comment by valassi** [comment]
Hi @oliviermattelaer this is now ready to be merged.

I completed my tests and all looks good
- There are no crashes #806 in gq_ttq for HIP anymore (because -O2 is used instead of -O3)
- In HIP tests on AMD GPUs, I see essentially *no performance degradation* from the fact that I use -O2 instead of -O3

En passant, now I also added the getCompiler() tag that decodes HIP version from defines.

Ready to go for me.

**Comment by valassi** [comment]
PS About the fact that there is no performance degradation

```
git diff --no-ext-diff e41c7ff1a 0c947d1d5 tput/logs_ggttgg_mad/log_ggttgg_mad_d_inl0_hrd0.txt
...
-DATE: 2024-09-19_19:08:34
+DATE: 2024-09-18_17:15:56
 
 On uan01 [CPU: AMD EPYC 7A53 64-Core Processor] [GPU: AMD INSTINCT MI200]:
 =========================================================================
@@ -30,36 +30,36 @@ INFO: The following Floating Point Exceptions will cause SIGFPE program aborts:
 Process                     = SIGMA_SM_GG_TTXGG_HIP [clang 17.0.0] [inlineHel=0] [hardcodePARAM=0]
 Workflow summary            = HIP:DBL+CXS:HIRDEV+RMBDEV+MESDEV/none+NAVBRK
 FP precision                = DOUBLE (NaN/abnormal=0, zero=0)
-EvtsPerSec[Rmb+ME]     (23) = ( 1.208699e+05                 )  sec^-1
-EvtsPerSec[MatrixElems] (3) = ( 1.258349e+05                 )  sec^-1
-EvtsPerSec[MECalcOnly] (3a) = ( 1.258584e+05                 )  sec^-1
+EvtsPerSec[Rmb+ME]     (23) = ( 1.204596e+05                 )  sec^-1
+EvtsPerSec[MatrixElems] (3) = ( 1.259417e+05                 )  sec^-1
+EvtsPerSec[MECalcOnly] (3a) = ( 1.259568e+05                 )  sec^-1
 MeanMatrixElemValue         = ( 3.804675e-02 +- 2.047289e-02 )  GeV^-4
-TOTAL       :     0.607053 sec
+TOTAL       :     0.715128 sec
 INFO: No Floating Point Exceptions have been reported
-     1,491,254,700      cycles:u                         #    2.509 GHz                      (75.96%)
-         2,542,523      stalled-cycles-frontend:u        #    0.17% frontend cycles idle     (75.44%)
-         5,449,723      stalled-cycles-backend:u         #    0.37% backend cycles idle      (75.46%)
-     1,937,303,891      instructions:u                   #    1.30  insn per cycle         
-                                                  #    0.00  stalled cycles per insn  (74.40%)
-       0.660947918 seconds time elapsed
+     1,635,437,665      cycles:u                         #    2.817 GHz                      (74.94%)
+         2,495,684      stalled-cycles-frontend:u        #    0.15% frontend cycles idle     (76.17%)
+         7,104,110      stalled-cycles-backend:u         #    0.43% backend cycles idle      (76.53%)
+     2,096,604,985      instructions:u                   #    1.28  insn per cycle         
+                                                  #    0.00  stalled cycles per insn  (74.05%)
+       0.853269091 seconds time elapsed
```

**Comment by oliviermattelaer** [comment]
Perfect, thanks

Olivier

**Comment by valassi** [comment]
Thanks @oliviermattelaer !
Very good, merging

**Pull request merged**
