### PR TITLE
Sr new repo layout

### PR DESCRIPTION
**Pull request by roiser**
New repository layout as discussed in mail thread, mainly moving to a structure

- epoch0/
   -  cpp/
   - fortran/
- epoch1/
   -  cuda/
   - alpaka/
   - kokkos/
   - hipsycl/
   - oneapi/
- tools/

from the old directory examples/[gpu|kokkos]. The remaining directories in examples/gpu have been removed. See also attached pdf for details 

[20201006-madgraph-repo-proposal.pdf](https://github.com/madgraph5/madgraph4gpu/files/5480105/20201006-madgraph-repo-proposal.pdf)

### CODE REVIEW

**Comment by roiser** [comment]
Hi @valassi @hageboeck I presume the content of the new directories should be equal to what is currently in the old structure in upstream/master. Could you pls x-check? best

**Comment by hageboeck** [comment]
The code looks correct, but the rebasing failed somehow. I suggest to take the current master, and apply the "move the files" commits on top of that.

**Comment by valassi** [comment]
Hi Stefan, I think that Stephan is more expert in git and can help you better.
I just see that a merge failed on my master (which is the same as the upstream master)
```
[avalassi@itscrd03 bash] ~/GPU2020/madgraph4gpu> git diff upstream/master
[avalassi@itscrd03 bash] ~/GPU2020/madgraph4gpu> git merge roiser:sr-new-repo-layout 
merge: roiser:sr-new-repo-layout - not something we can merge
```
I am actually a bit surprised that your PR includes all the recent commits from me and Stephan.
I thought that you would take the latest master, apply a script to restructure the repo and just commit that (which is probably what Stephan is sugesting). In any case this would probably give a cleaner repo than trying to backport my and Stephan's changes over a new repo with different file paths.

**Comment by roiser** [comment]
> Hi Stefan, I think that Stephan is more expert in git and can help you better.
> I just see that a merge failed on my master (which is the same as the upstream master)
> 
> ```
> [avalassi@itscrd03 bash] ~/GPU2020/madgraph4gpu> git diff upstream/master
> [avalassi@itscrd03 bash] ~/GPU2020/madgraph4gpu> git merge roiser:sr-new-repo-layout 
> merge: roiser:sr-new-repo-layout - not something we can merge
> ```
> 
> I am actually a bit surprised that your PR includes all the recent commits from me and Stephan.
> I thought that you would take the latest master, apply a script to restructure the repo and just commit that (which is probably what Stephan is sugesting). In any case this would probably give a cleaner repo than trying to backport my and Stephan's changes over a new repo with different file paths.

Ah maybe the confusion comes from how I did it. Actually what happened is that I created the branch some time ago and re-ordered the repo. Then I just rebased this branch with upstream/master and git seems to have recognised all the moved files. But if its less confusing we can re-do all the re-ordering starting from the latest master. It's not so much work either.

**Review by hageboeck — APPROVED** [review]
👍

**Comment by valassi** [comment]
Hi Stefan, thanks, much better :-)
I did a git merge roiser/sr-new-repo-layout without issues, an dit only shows the 5 commits where you move things around.

One minor comment, it may actually be useful to keep somewhere the original output of MG at the start of each epoch, before any manual changes on our side. This is probably what used to be in auto. On the other hand I have not really looked at it in months, so I guess it is useless? Lets say. it would be nice to understand how to find it back in the repo.

Otherwise, all ok, please go ahead
Thanks
Andrea

**Review by valassi — APPROVED** [review]
OK!

**Comment by valassi** [comment]
Hi @roiser and @hageboeck sorry to reopen the discussion, I have a question: when I look at https://github.com/madgraph5/madgraph4gpu/commits/master/epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/CPPProcess.cc
I am unable to find any history, this appears to be a new file, while actually it has been renamed from examples/gpu/eemumu_AV somewhere. Is this something which somehow can be fixed, or is this unavoidable with git? I thought that "git mv" would automatically keep some history.

I am asking because I need to dig up why I made some changes (to answer #57). Not a big issues because I know where to look, but it would be nice to have this automatic if possible, especiallyt if in the future we need further restructuring. Thanks! Andrea

**Comment by roiser** [comment]
Hi @valassi, git itself is able to follow the history via the --follow option of git log, so on the command line you can follow and I checked this works nicely. github.com seems not to be able to provide this info though I'm afraid.

**Comment by valassi** [comment]
Hi Stefan, thanks. Yes actually I also noticed in the meantime that the "blame" button does provide useful history actually. It is just the "history" button that is empty. So it seems to be a limitation of github. Ok no problem, good to know that at least blame and __follow do work nicely. Thanks! Andrea

**Pull request merged**
