### PR TITLE
upgrade to Olivier's latest "black box" changes

### PR DESCRIPTION
**Pull request by valassi**
WIP: upgrade to Olivier's latest "black box" changes - but this does not fix gqttq xsec #630

### CODE REVIEW

**Comment by oliviermattelaer** [comment]
I'm going to fix soon (since the problem is identified, just need to understand how to nicely fix it).
So you may want to wait for this (or not as you want)

**Comment by oliviermattelaer** [comment]
@valassi 
Please check https://github.com/mg5amcnlo/mg5amcnlo/commit/ecf424f8fa8f11b55cffeee4a15fdffba527897b
which include the latest fix concerning the cross-section. 
They are still some issue to be fixed in #678 but technically only in the way the events are written on disk, not on the cross-section.

**Comment by valassi** [comment]
> @valassi Please check [mg5amcnlo/mg5amcnlo@ecf424f](https://github.com/mg5amcnlo/mg5amcnlo/commit/ecf424f8fa8f11b55cffeee4a15fdffba527897b) which include the latest fix concerning the cross-section. They are still some issue to be fixed in #678 but technically only in the way the events are written on disk, not on the cross-section.

Hi Olivier, thanks, done. I am running the tests on the code including your latest changes now

**Comment by valassi** [comment]
CI tests are ok - self merging

**Pull request merged**
