### PR TITLE
add support for ROCRAND (via HIPRAND)

### PR DESCRIPTION
**Pull request by valassi**
As suggested by @roiser in PR #801, this is a WIP PR for adding rocrand (I think in the end it will be rocrand actually) support.

Very much WIP, more than the implementation itself there was a lot of logic in env variables and switches to sort out, I focused on that first

### CODE REVIEW

**Comment by valassi** [comment]
NB this is based on PR #801, it is just a few additions on top of that, but I would keep them separate

**Comment by valassi** [comment]
The status at this point is that
- the code builds
- gcheck.exe runs in rocranddevice, but produces nan MEs
- gcheck.exe and check.exe fail in rocrandhost

**Comment by valassi** [comment]
> The status at this point is that
> 
>     * the code builds
> 
>     * gcheck.exe runs in rocranddevice, but produces nan MEs

This is fixed

>     * gcheck.exe and check.exe fail in rocrandhost

This I have now understood as being simply not supported yet. I checked and I always get a status 1000, not implemented. This is not surprising, see https://github.com/ROCm/hipRAND/blob/be4f5a97d55b6a38733a7a66970d13aef6c8944f/library/src/amd_detail/hiprand.cpp#L103
```
hiprandStatus_t HIPRANDAPI hiprandCreateGeneratorHost(hiprandGenerator_t* generator,
                                                      hiprandRngType_t    rng_type)
{
    (void)generator;
    (void)rng_type;
    return HIPRAND_STATUS_NOT_IMPLEMENTED;
}
```
Also see issue 76 in https://github.com/ROCm/hipRAND/issues. This is actively being worked on in Dec 2023.

I would do the following:
- I would keep using the hiprand API rather than the rocrand API, because it is just much simpler (closer to curand)
- I would complete this PR with device only support, and postpone host support for hiprand

In any case none of this is relevant yet to Madgraph production (we are still at Fortran ranmar). We can wait for the hiprand host api...

**Comment by valassi** [comment]
This is almost ready for review
- I have cleaned up all names to indicate that this uses hiprand, rather than rocrand
- I have clarified that hiprand host is not supported yet so I use common c++ random
- I have clarified that hiprand ordering is also not supported yet, so I just skip that for the moment 
- I have merged here upstream/master from PR #801 and #811

I am now rerunning the final battery of tests, this will be the next one on the list

**Comment by valassi** [comment]
This was now complete and fully tested, before the merge of PR #368.

However, the merge of PR #368 introduces many not completely obvious conflicts, so I leave this in WIP. I willl fix those conflicts and make this ready for review.

**Review by oliviermattelaer — APPROVED** [review]
Since I can not test on HIP, I have just read the code change and do not spot anything relevant to comment (but stuff not related to this PR).
In my opinion this can go trough, @roiser  do you agree? ( I would wait for his confirmation)

**Comment by oliviermattelaer** [comment]
@roiser just to ping you such that you can approve this such that we can move forward on it too

**Comment by roiser** [comment]
quick code inspection, this also looks fine, again didn't look at the makefile changes but sure ok

Really minor comment and I propose not to revert this, but there is no need to bump up the copyright year numbers, see e.g. blog post https://matija.suklje.name/how-and-why-to-properly-write-copyright-statements-in-your-code (got the link from the CERN open source policy office OSPO)

**Review by roiser — APPROVED** [review]

**Comment by valassi** [comment]
> quick code inspection, this also looks fine, again didn't look at the makefile changes but sure ok

thanks @roiser for the approval, I will merge now

> Really minor comment and I propose not to revert this, but there is no need to bump up the copyright year numbers, see e.g. blog post https://matija.suklje.name/how-and-why-to-properly-write-copyright-statements-in-your-code (got the link from the CERN open source policy office OSPO)

interesting point... i was actually going to propose that we update all copyright statements to be 2020-2024 in the code, now I am a bit less sure after reading your blog post

i must say i still have a preference for having all copyright statements updated to 2020-2024: i mean that post suggests you _do not need_ to update the years, but it is _not saying that you should absolutely not do that_... I find it visually more clear on the one hand, and on the other hand it _IS_ true that we are continually updating the code... and in any case yes 50-70 years are a long time, so it makes a little difference...

I think I would especialy like a self consistent practice throughout the code: for instance, we put 2020-2024 everywhere, or we put 2020 (or year of first publication if >2020) everywhere... thoughts?

anyway, I am merging this

**Comment by valassi** [comment]
PS I moved the copyright discussion to issue #817

**Comment by valassi** [comment]
Quick update. The following issues were updated in https://github.com/ROCm/hipRAND/issues
- issue 75: hiprand ordering implemented in rocm 6.2 (sep 2024)
- issue 76: hiprand status implemented in rocm 6.2 (sep 2024)

On LUMI the default is still ROCm 6.0. So this still needs to wait a bit before testing.

**Pull request merged**
