### PR TITLE
Fixes for clang16, gcc14.2, HIP/AMD

### PR DESCRIPTION
**Pull request by valassi**
This is  a WIP PR with fixes for clang16, gcc14.2, HIP/AMD
- work around for FPE on HIP ROCM6.0 clang #1003 (and other minor issues on LUMI #998)
- work around for FPE on clang 16 #1005 
- fix cxtype_ref on gcc14.2 #1004 

I will run some tests like this, then if they are ok this can probably be merged, even if there are certainly other similar issues to be fixed

### CODE REVIEW

**Comment by valassi** [comment]
Hi @oliviermattelaer this is ready for review, can you please have a look?

Summary
- in EventStatistics.h, disable optimizations on clang in a function to work around some FPEs (crash only if optimized code... not a fix, but it avoids the problem)
- in cudacpp.mk, fix some link issues on LUMI for HIP
- in cxtype_ref headers, separate const and non-const operator to avoid build errors with the most recent gcc's
- plus codegen and rerun some tests

Thanks

**Comment by oliviermattelaer** [comment]
Sounds reasonable to me. Go for it.

Thanks,

Olivier

**Comment by valassi** [comment]
> Sounds reasonable to me. Go for it.

Thanks to you Olivier. Will merge soon.

I just added also some commit logs for LUMI AMD GPUs #998 (and some commented out build options to debug #806 on LUMI)

I will merge when the CI completes.

**Comment by valassi** [comment]
The CI passed. Merging.

**Pull request merged**
