### PR TITLE
update the mg5amcnlo submodule to the latest commit in branch gpucpp

### PR DESCRIPTION
**Pull request by valassi**
Hi @oliviermattelaer as discussed in PR #801.

This WIP PR updates the mg5amcnlo submodule to the latest commit in branch gpucpp.

Note: code generation now fails (well it is actually treatcards in my case) because reset_simd in banner.py throws an exception. It would be enough to change that exception to a warning for the time being, an dthings would be better.

Or otherwise we can take the time to understand better what goes on.

### CODE REVIEW

**Comment by oliviermattelaer** [comment]
Is your issue is this?
```
Command "generate_events run_01" interrupted with error:
InvalidCardEdition : value 'fortran' for entry 'cudacpp_backend' is not valid.  Preserving previous value: 'CPP'.
	allowed values are Fortan, CPP, CUDA

Please report this bug on https://bugs.launchpad.net/mg5amcnlo
More information is found in 'ME5_debug'.
Please attach this file to your report.
```
I'm looking about that issue (not sure if this is mg5 or the plugin), I can not do any run as long as this is not solved (and therefore can not run on #801), so I'm investigating it for the moment

**Comment by valassi** [comment]
Hi Olivier, sorry NO! I was wrong.

Code generation succeeds if I update mg5amcnlo to gpucpp on top of the master of madgraph4gpu. I will test this here.

Instead I have the impression that code generation fails if I update mg5amcnlo to gpucpp on top of the jt774 branch (PR #801) of madgraph4gpu. So it seems that there is an interplay of my/Jorgen's changes for HIP and your changes for mg5amcnlo? I need to check better, sorry.

If the above is confirmed, I suggest:
- I do go ahead and update mg5amcnlo to gpucpp, i.e. I merge this PR #811 
- Then I also do the same in #801, and I fix that one...

Sounds ok? But let me check before I say stupid things. It will take me time to run all tests however, will merge this tomorrow at the earliest

**Comment by valassi** [comment]
> Is your issue is this?
> 
> ```
> Command "generate_events run_01" interrupted with error:
> InvalidCardEdition : value 'fortran' for entry 'cudacpp_backend' is not valid.  Preserving previous value: 'CPP'.
> 	allowed values are Fortan, CPP, CUDA
> 
> Please report this bug on https://bugs.launchpad.net/mg5amcnlo
> More information is found in 'ME5_debug'.
> Please attach this file to your report.
> ```
> 
> I'm looking about that issue (not sure if this is mg5 or the plugin), I can not do any run as long as this is not solved (and therefore can not run on #801), so I'm investigating it for the moment
> 
> UPDATE: that one was easy to fix (it is obvious but my brain hide to issue for me for so so long ....)

No my issue was different... but again, I think only in jt774 ie PR 801

**Comment by valassi** [comment]
Hi Olivier, thanks. Ok thanks for confirming that this PR #811 and the gpucpp update is not urgent.

I will look at the jt774 instead then, thanks for adding the fix directly there.

**Comment by valassi** [comment]
> Instead I have the impression that code generation fails if I update mg5amcnlo to gpucpp on top of the jt774 branch (PR #801) of madgraph4gpu. So it seems that there is an interplay of my/Jorgen's changes for HIP and your changes for mg5amcnlo? I need to check better, sorry.

Ok not sure anymore why/where I saw an exception in reset_simd. Now code generation with this update seems ok also in jt774? But I will postpone this anyway. I will do PR #801 WITHOUT this update. And convert this to WIP (and postponed)

**Comment by oliviermattelaer** [comment]
Looks like we hit "could not check for binary extension: HTTP 403: API rate limit exceeded for installation ID 13042647. "
which might have trigger some false alarm in the recent commit/PR... I guess we do too much work for github ;-)

**Comment by valassi** [comment]
Hi Olivier, in the end it was easier for me to do this one first.

I upgraded mg5amcnlo to the current (well yesterday's) gpucpp branch, have regenerated the code and run all tests.

If this is ok for you I would go ahead and merge.

Apart from generated code and test logs, there are no changes other than that in MG5aMC/mg5amcnlo.

It should be a trivial change, but still please approve it ;-)

Thanks
Andrea

**Review by oliviermattelaer — APPROVED** [review]
perfect thanks

**Comment by valassi** [comment]
Thanks a lot Olivier, now merging

**Pull request merged**
