### PR TITLE
Add bin/madevent to the madgraph4gpu repo for all processes

### PR DESCRIPTION
**Pull request by valassi**
Hi @oliviermattelaer this is a very simple PR that __only__ affecs madgraph4gpu repos. It does not touch CODEGEN.

It adds bin/madevent to the madgraph4gpu repo for all processes, in particular BSM processes where it was missing (while for SM processes it was there). I had to modify the .gitignore (again __only__ of madgraph4gpu, no change in CODEGEN).

The reason is that I need bin/madevent to launch bin/generate_events from a repo process when I modify the runcards. (The treacards step uses it).

I hope it is not controversial, can you approve please? I need this to investigate the cross section crashes in susy #826 

Thanks
Andrea

### CODE REVIEW

**Comment by valassi** [comment]
PS Ah yes this includes many changes also because it is the first full regeneartion with your PR 835: so launch_plugin.py and runcards are modified from your patch Olivier

**Comment by valassi** [comment]
PPS and just for further explanation, I removed madevent and a few other files from epochX/cudacpp/.gitignore because it was/is ALREADY in the  .gitignore of all SubProcesses/P* generated directories

**Review by oliviermattelaer — APPROVED** [review]
Sure go ahead.

Thanks

Olivier

**Comment by valassi** [comment]
Ok thanks! I will merge this. Andrea

**Pull request merged**
