### PR TITLE
Sycl fix nans

### LINKED ISSUE #294: Sycl code returns nan
The sycl code is returning nan
```
NumMatrixElements(notNan)  = 0
MeanMatrixElemValue        = ( nan +- -nan )  GeV^-4
[Min,Max]MatrixElemValue   = [ nan ,  nan ]  GeV^-4
StdDevMatrixElemValue      = ( -nan                 )  GeV^-4
MeanWeight                 = ( -nan +- -nan )
[Min,Max]Weight            = [ 2.812272e+01 ,  2.812272e+01 ]
StdDevWeight               = ( -nan                 )
```

### PR DESCRIPTION
**Pull request by nscottnichols**
1. changed device selection to better handle multiple devices with same vendor id
2. Fixes #294 
3. free device memory to prevent memory leaks
4. some small structural changes for includes as workaround for compiling on AMD devices (can probably write some wrappers instead of including `*.cc` files for an actual fix)

### CODE REVIEW

**Comment by lfield** [comment]
The build fails for me. 
`clang++ -v -ffast-math -pthread -fsycl -fsycl-targets=nvptx64-nvidia-cuda-sycldevice --cuda-include-ptx=sm_70 -fsycl-unnamed-lambda --cuda-path=/usr/local/cuda-10.2/ -I src -I SubProcesses/P1_Sigma_sm_gg_ttxgg/ -I ../../../tools/ SubProcesses/P1_Sigma_sm_gg_ttxgg/CPPProcess.cc src/rambo.cc src/read_slha.cc src/Parameters_sm.cc SubProcesses/P1_Sigma_sm_gg_ttxgg/check_sa.cc -o SubProcesses/P1_Sigma_sm_gg_ttxgg/gcheck_sa.exe`


` "/opt/sycl_workspace/llvm/build/bin/llvm-link" /tmp/CPPProcess-23e2dc.bc /tmp/rambo-f76f15.bc /tmp/read_slha-2200af.bc /tmp/Parameters_sm-0702a3.bc /tmp/check_sa-35b4a3.bc -o /tmp/CPPProcess-2d60f4.bc --suppress-warnings
error: Linking globals named '_ZN11rambo2toNm017getMomentaInitialEdPdN2cl4sycl7nd_itemILi3EEE': symbol multiply defined!
clang-12: error: sycl-link command failed with exit code 1 (use -v to see invocation)
`

**Comment by nscottnichols** [comment]
`rambo.cc` and `CPPProcess.cc` are now included (needed for AMD builds)
Try compiling with:
`clang++ -v -ffast-math -pthread -fsycl -fsycl-targets=nvptx64-nvidia-cuda-sycldevice --cuda-include-ptx=sm_70 -fsycl-unnamed-lambda --cuda-path=/usr/local/cuda-10.2/ -I src -I SubProcesses/P1_Sigma_sm_gg_ttxgg/ -I ../../../tools/ src/read_slha.cc src/Parameters_sm.cc SubProcesses/P1_Sigma_sm_gg_ttxgg/check_sa.cc -o SubProcesses/P1_Sigma_sm_gg_ttxgg/gcheck_sa.exe`

**Comment by lfield** [comment]
It builds but fails to run if no options are specified. 
```
./gcheck_sa.exe 1 8 1
Segmentation fault (core dumped)
```

**Comment by nscottnichols** [comment]
Ah, I see the issue here. I wasn't having segfaults on my device so I didn't catch it. What are your thoughts on default device selection (without using flags)? Should we have a prompt like before this PR where the user selects the device via input, default to device 0, or use the `gpu_selector`?

**Comment by lfield** [comment]
Defaulting to device 0 should be fine but don't forget to handle the scenario where there are no devices.

**Comment by lfield** [comment]
Works for me.

**Pull request merged**
