### PR TITLE
enable ARM NEON (128 bit) vector registers via compiler defined macros

### PR DESCRIPTION
**Pull request by roiser**
enable ARM NEON

### CODE REVIEW

**Comment by valassi** [comment]
Hi @roiser I added several comments about this in #221.

Bottom line:
- it presently does not support a way to disable SIMD (ie the 'none' option)
- it addresses the sam eissues as 128-bit vsx on Power9, but in a different way
- for these reasons I would modify this to use the same approach as on Power9 (ie add -D__SSE42__ if you want 128bit neon vectors, and add nothing if you want to keep no simd)
- later on this should probably be changed to use a define like -Dmg_prefer_vector_width128 instead of -D__sse42, and use that on all of intel, power9, arm

**Comment by valassi** [comment]
Hi @roiser I am closing this one and replacing it by PR #425. Please have a look (but still in WIP)... thanks!

**Comment by valassi** [comment]
I have now merged #425 which includes and replaces this #421.

**Comment by roiser** [comment]
* later on this should probably be changed to use a define like -Dmg_prefer_vector_width128 instead of -D__sse42, and use that on all of intel, power9, arm

On this point, yes I think we should go away from Intel specific names and use generic ones. All very fine with me, thanks

**Pull request closed without merging**
