### PR TITLE
'make install' improvements

### PR DESCRIPTION
**Pull request by valassi**
A few improvements in 'make install'

As discussed in #304:
-    now make install does not work with "USEBUILDDIR=1", ie it only installs the version that is locally built
-    in that case, ie if USEBUILDDIR is unset, I have forgotten to copy the .build.tag file (eg .build.none_d_inl0_curdev) to the lib directory

In addition:
- improve the logic so that .h and .o are only copied if they are not already there
- add an avxall-install target

### CODE REVIEW

**Comment by valassi** [comment]
Hi @roiser let me know if you hav eobjectsions or suggestions
thanks
a

**Comment by valassi** [comment]
Argh I need on etiny fix, the modelsm stuff in the makefiles..

**Comment by valassi** [comment]
ok now ready for review and merge after a small fix

**Review by roiser — APPROVED** [review]
all good, thx

**Pull request merged**
