### PR TITLE
Complete PR 955 for goodhel (resync to master, regenerate code)

### PR DESCRIPTION
**Pull request by valassi**
This is a WIP PR to extend Olivier's PR #955 about master_goodhel.

It is meant to fix the pp_tt012j bug #872 using a different approach than my proposal in PR #935.

For the moment I just merged the latest master into Olivier's PR and regenerated gg_tt.mad, fixing all conflicts and adding a new mg5amcnlo branch.

Now I will run the CI and in parallel do more tests. Probably I will add bits and pieces of my 935 here.

### CODE REVIEW

**Comment by valassi** [comment]
All CI tests have passed, so the issue pp_tt012j #872 is fixed
image

**Comment by valassi** [comment]
Hi @oliviermattelaer this is my completion of your master_ggodhel.

There are many diffs unfortunately because your mastergoodhel does not include the latest master.

In this PR anyway I am not doing much
- merge master into your PR
- regenerate all code in the repo
- rerun some manual tests

Specifically
```
[avalassi@itscrd90 gcc11/usr] /data/avalassi/GPU2023/madgraph4gpuX/epochX/cudacpp> git log --oneline upstream/master..HEAD
4c35b61f3 (HEAD -> goodhel, origin/goodhel, ghav/goodhel) [goodhel] ** COMPLETE GOODHEL ** rerun 30 tmad tests on itscrd90 - all as expec>
48fa9bfeb [goodhel] rerun 102 tput tests on itscrd90 - all ok
016433bea [goodhel] regenerate all processes - erase them and add them from scratch, because many things changed in 3.6.0
94f9f9bf0 [goodhel] rerun tmad ggtt test - all ok (even if now reset_cumulative_variable is no longer called)
ae6652c46 [goodhel] regenerate gg_tt.mad - add to the repo couplings3.f and PDF/lep_densities, which I had previously forgotten
d42666dc2 [goodhel] regenerate CODEGEN patch from gg_tt.mad (note that genps.inc is now longer needed)
2cd6764ec [goodhel] regenerate gg_tt.mad - check all is ok, no change
002dee873 Merge remote-tracking branch 'upstream/master' into goodhel
d582f6c86 [goodhel] move to upstream/master codegen logs of gg_tt for easier merging
a08d91f43 [goodhel] update MG5AMC from ffb7a2e01 (gpucpp_goodhel) to 0c754d6d8 (valassi_goodhel, i.e. gpucpp plus the merge of gpucpp_goo>
b986a8258 [goodhel] regenerate gg_tt.sa just as a cross check: the only change is that 3.5.3 becomes 3.6.0, but the code is identical
763479db5 [goodhel] regenerate gg_tt.mad using the current CODEGEN from upstream/master_goodhel
c448e89db (upstream/master_goodhel) random test
b304cc905 fixing a patch that was relying on imirror
df130b077 temporary fix to set limhel to 0 for cudacpp
76ba27a50 change mg5amc version to use
a8262594c fix patch to be compatible with mg5 branch gpucpp_goodhel
```

If you agree, I wil 
- merge this into master_ggodhel #986
- andthen merge master_goodhel into master #955

**Comment by oliviermattelaer** [comment]
So yes this is good to be merged (I did not review the diff and just trust you on your change)
So yes all those 4 PR can move forward.

Thanks,

Olivier

**Comment by valassi** [comment]
> So yes this is good to be merged (I did not review the diff and just trust you on your change)
> So yes all those 4 PR can move forward

Hi @oliviermattelaer , thanks.

Unfortunately, as discussed, now that the june24 stuff has been merged into gpucpp and master, there are conflicts to solve.

Anyway, here I have just added a few commits that address those merge conflicts
- in madgraph4gpu, the current goodhel here in 986 is mergeable to gpucpp without conflicts (it includes the june24 stuff now)
- in mg5amc, this 986 is based on a branch valassi_goodhel_june24 in WIP PR https://github.com/mg5amcnlo/mg5amcnlo/pull/139

Apart from the fact that the way I fixed conflicts must be checked (especially for the tests), my main issue is that now a tmad ggtt test fails, see #991

**Comment by oliviermattelaer** [comment]
So the isue with #991 is fixed and part of the PR #992.

**Comment by valassi** [comment]
> So the isue with #991 is fixed and part of the PR #992.

Thanks a lot @oliviermattelaer ! Yes I confirm what you said.

Let's keep this open, it should automatically appear as merged when we merge #992.

In any case I will mark that #992 fixes also the issues #872 and #950 that are fixed in this #986 and the underlying #955

**Comment by valassi** [comment]
No, actually this was into master_goodhel. This is no longer necessary. It has been included in master_for360 and will be included in master via #992. Closing this, to start a cleanup.

**Pull request closed without merging**
