### PR TITLE
Fix segfault from constexpr_math.h and adapt testmisc.cc to higher tolerances when running through valgrind

### PR DESCRIPTION
**Pull request by valassi**
This is a PR to
- fix segfault from constexpr_math.h #903
- adapt testmisc.cc to higher tolerances when running through valgrind #906

This was motivated by the WIP on adding testst for channelid #896 within the WIP on master_june24 #882

Note: the latter is still blocked by another segfault #907

### CODE REVIEW

**Comment by valassi** [comment]
Hi @oliviermattelaer can you please review?

Hopefully not controversial.

Note: this includes also both PR #900 on omp and PR #905 on clang. So it might be better to merge those two independently first

**Review by oliviermattelaer — APPROVED** [review]
Ok this sounds good.

Just like I said in #905, I'm confused why you forbid any activation the openmp mode.
Maybe the best is to "remove that particular" commit and then merge the rest. 
Or wait that #905 is accepted before merging this... (or any other solution)

I put this as approve anyway,

Olivier

**Comment by valassi** [comment]
> Ok this sounds good.
> 
> Just like I said in #905, I'm confused why you forbid any activation the openmp mode. Maybe the best is to "remove that particular" commit and then merge the rest. Or wait that #905 is accepted before merging this... (or any other solution)
> 
> I put this as approve anyway,
> 
> Olivier

Thanks Olivier :-)

The clang #905 is now modified as agreed, and merged.

I have updated this, I will merge it when the CI has been executed

**Comment by valassi** [comment]
The CI completed with
163 successful and 6 failing checks 
This is as expected

Merging now

**Pull request merged**
