### PR TITLE
remove un-necessary patch

### PR DESCRIPTION
**Pull request by oliviermattelaer**
The point is that the function
self.compile('madevent')
is already catched by the CPP/CUDA interface of launch_plugin.py and does ensure that 
compile('madevent') actually compiles the required exectuble. So they are no need to change the local copy of the  "upstream" code (which might not be used anyway since the upstream one can have priority).

So since this is already handle correctly where you run the unpatch file, they are no reason to patch them...
So I did remove the patch in this PR. (see also [#844](https://github.com/madgraph5/madgraph4gpu/issues/844))

### CODE REVIEW

**Comment by oliviermattelaer** [comment]
This CI crash on a quite funy way:

```
 ../../src/Parameters_MSSM_SLHA2.h:826:58: error: conversion from ‘mg5amcCpu::fptype_sv’ {aka ‘__vector(2) double’} to non-scalar type ‘const mgOnGpu::cxsmpl<double>’ requested
  826 |         constexpr cxsmpl<double> mdl_G__exp__2 = ( ( G ) * ( G ) );
      |                                                  ~~~~~~~~^~~~~~~~~
make[2]: *** [cudacpp.mk:700: build.sse4_d_inl0_hrd0/runTest_cpp.o] Error 1
```
So this sounds like not related to this PR but to (another) type missmatch?

What do you think @valassi?

**Comment by oliviermattelaer** [comment]
@valassi, just to remind us about this PR here, would you have any conceptual problem with this?
if not, I can probably update the mg5amc commit to avoid the conflict and repropose this.

**Review by valassi — APPROVED** [review]
Hi @oliviermattelaer that's good for me.

Or better: I trust you on this, as it only touches gen_ximprove.py and madevent_interface.py, and I am not routinely testing those. So you certainly know better.

Only two issues:
- the MG5AMC conflict must be fixed
- the processes must be regenerated

Both issues are solved in my PR #939. So you could merge that branch of mine here and then merge into master, or merge directly my 939.

Thanks
Andrea

**Comment by valassi** [comment]
> Only two issues:
> 
>     * the MG5AMC conflict must be fixed
> 
>     * the processes must be regenerated
> 
> 
> Both issues are solved in my PR #939. So you could merge that branch of mine here and then merge into master, or merge directly my 939.

Thanks Olivier for approving my #939 :-)

I had forgotten the conflicts. I thought I would merge this 849 into master first, and then 939 into master, but this will not work. I will instead merge 939 here, and then this 849 into master.

**Comment by valassi** [comment]
Ok I merged 939 here into less_patch, fixing the conflicts.

Waiting for the CI to complete, then I will merge this into master.

**Comment by valassi** [comment]
Ok CI completed with 6 failures as expected (susy and pptt012j), merging

image

**Pull request merged**
