### PR TITLE
Move default fptype to m in cudacpp makefiles and scripts

### LINKED ISSUE #995: Reminder: move default fptype to m in cudacpp makefiles and scripts
Just a minor reminder: move default fptype to m in cudacpp makefiles and scripts

Presently the code is inconsistent:
- cudacpp makefiles assume fptype=d as default
- madevent runcards assume fptype=m as default

This means that, if one wants to prebuild the code before creating a gridpack, the d build is not used because m is needed

### PR DESCRIPTION
**Pull request by valassi**
This is a small PR to move default fptype to m in cudacpp makefiles and scripts

It fixes #995

### CODE REVIEW

**Comment by valassi** [comment]
Voila I changed the target so now it's easier to review.

But I would then merge it to master once reviewd and approved

**Comment by oliviermattelaer** [comment]
So this change is something that I can approve (but I do not approve the base branch, so we either have to wait or to cherry-pick).

**Comment by valassi** [comment]
Moving back to ready for review and merging, after doing the requested changes in the base PR #1016.

**Review by oliviermattelaer — APPROVED** [review]
I confirm that this is good to go.

Thanks,

Olivier

**Comment by valassi** [comment]
> I confirm that this is good to go.
> 
> Thanks,
> 
> Olivier

Thanks Olivier :-)

(For info: I force pushed some changes in comments, the FPTYPE runcard is called floating_type, not cudacpp_backend...)

Merging now
Andrea

**Comment by valassi** [comment]
(And I changed the base: merging to master, not to a fake branch that I had created only to make changes more visible)

Merging

**Pull request merged**
