### PR TITLE
Regenerate code (and susyggt1t1 reference logs) with couplings fix from PR 918

### PR DESCRIPTION
**Pull request by valassi**
Regenerate code with couplings fix from PR 918

This is simply an extension of PR #918 adding code regeneration - and I will add a few more manual tests probably

### CODE REVIEW

**Comment by valassi** [comment]
PR 918 is confirmed to fix #826 about zero cross section in a susy process, itself caused by #862 about couplings order

**Comment by valassi** [comment]
Hi @oliviermattelaer this is ready for review for me can you have a look after your holidays please?

In addition to the fix in #918, this includes
- the regeneration of all code generated processes
- the update of the reference log for susyggt1t1 (normally this should have showed up in the CI, but I suspect there is a bug #937 that I will have a look at)

I suggest approving this, then mering 918, then merging this one.

**Review by oliviermattelaer — APPROVED** [review]
Just nitpicking on two pep08 stype of writing code (that are technically in the other PR already).
But ok, this is good to go.

Thanks,

Olivier

**Comment by valassi** [comment]
> Just nitpicking on two pep08 stype of writing code (that are technically in the other PR already).

Thanks I committed your suggestions (can you tell me how you check pep08 please? coul dbe useful for me too)

> But ok, this is good to go.

Thanks :-)

I will resolve conflicts (I have just merged #849 and #939) an dthen merge

**Comment by valassi** [comment]
Ok the CI has 3 failing checks.
image


I will merge 918 an dthen merge this one.

**Comment by valassi** [comment]
I had to merge upstream/master with 918 into this one.

But there is no change anywhere, no need to rerun teh CI.

I wil ljust merge.

**Pull request merged**
