### PR TITLE
first version of ee_mumu coming from madgraph --some PR still need to…

### PR DESCRIPTION
**Pull request by oliviermattelaer**
Hi,

This is the current output generated by MG5aMC which is relatively close to the current output of epoch1.
I likely miss some recent (less than two weeks old) PR. If you can put those in the comment below, this will help me to check them one by one and to include the associate change.

The mG5aMC code is not yet running for gg>tt~gg but this will likely be working soon.

### CODE REVIEW

**Comment by roiser** [comment]
Hi @oliviermattelaer there is #61 which needs to be still approved (I'll try to ping reviewers) but includes also some changes for the json output in epoch 1 ee-mumu

**Comment by oliviermattelaer** [comment]
Thanks Stefan, this should be in now

**Comment by oliviermattelaer** [comment]
@valassi @roiser @hageboeck 
The Cpp code is now compiling (but requires curand obviously so it needs cuda)

@hageboeck should we put the test for epoch2? would be nice to have it setup before merging this branch no?

**Comment by hageboeck** [comment]
Yes, let me check out the branch and see if I can get the test to run. You can take the commits once done.

**Comment by hageboeck** [comment]
@oliviermattelaer see #78. I managed to port the tests, and they fail. :-D

**Comment by hageboeck** [comment]
@oliviermattelaer I tried to push the commits to activate the CI on top, but I failed. I will reset. :-)

**Pull request merged**
