### PR TITLE
Master for360

### PR DESCRIPTION
**Pull request by oliviermattelaer**
Hi Andrea,

This is based on valassi/goodhel and only add one (non controversial) commit for being compatible with gpucpp_for360
(so this also point mg5amc to that commit/branch).

Currently in draft in order to test the CI (but since this is based on your commit, I do expect the same issue of missmatch)

But do not hesitate to cherry-pick this last commit to other branch since it should be fully fine to have it into master.

### CODE REVIEW

**Comment by oliviermattelaer** [comment]
Since all CI are working here, Let me remove the WIP.
I'm thrill that this was so easy :-)

Let's merge this !

Olivier

**Comment by valassi** [comment]
> Since all CI are working here, Let me remove the WIP.
> I'm thrill that this was so easy :-)

Hi @oliviermattelaer wow well done! :-)
Indeed, it seems too easy to be true ;-)

I am just having a quick look now on Sunday, then I will look better tomorrow during my work day. I will open a new branch where I just extend the work you have done here, and regenerate all code, and relaunch my usual tests.

But for the moment what I find great is that you have fixed all conflicts, and you are already up to date with the latest gpucpp in mg5amcnlo and with the latest master in madgraph4gpu. So this looks really good.

More tomorrow, thanks again Andrea

**Review by valassi — APPROVED** [review]
Hi @oliviermattelaer thanks a lot again, I confirm that this is good!

I suggest two other merges, before merging this one - but I mark this as approved
1. First we merge https://github.com/mg5amcnlo/mg5amcnlo/pull/140 into gpucpp in the mg5amcnlo repo (I approved the PR)
2. Then (or before 1, whatever) we merge https://github.com/madgraph5/madgraph4gpu/pull/997 into your master_for360
3. Finally (after the above two) we merge this https://github.com/madgraph5/madgraph4gpu/pull/992 into master

Let me know if you approve this, I can go aead and do the merges. (Or you do them, as you want)

**Comment by valassi** [comment]
Just for the record:
- this PR 992 from Olivier includes Olivier's 'goodhel' work in #955, which I have now closed, to fix the pp_tt012j xsec issue #872
- this PR 992 also includes my 'additional goodhel' work in #986 (needed to fix conflicts in 955), which I have also closed
- my proposal #935 to fix that bug 872 via reset_cumulative_variable is now obsolete: I kept 935 in WIP and might still merge it at some point, as it contains other tests and pp_tt (but the CODEGEN will be from this 992)
- this PR 992 will also be complemented by my #997 with code generation and some tests
- this PR 992 relies in mg5amcnlo on https://github.com/mg5amcnlo/mg5amcnlo/pull/140

**Comment by oliviermattelaer** [comment]
Yes we can move forward on this.

Great excelent, thanks

**Comment by valassi** [comment]
> Yes we can move forward on this.
> 
> Great excelent, thanks

Thanks a lot to you Olivier!

> I suggest two other merges, before merging this one - but I mark this as approved
> 
>     1. First we merge [Gpucpp for360 mg5amcnlo/mg5amcnlo#140](https://github.com/mg5amcnlo/mg5amcnlo/pull/140) into gpucpp in the mg5amcnlo repo (I approved the PR)
> 

This is merged

>     2. Then (or before 1, whatever) we merge [Additional fixes/tests over Olivier's master_for360 #997](https://github.com/madgraph5/madgraph4gpu/pull/997) into your master_for360
> 

This is also merged

>     3. Finally (after the above two) we merge this [Master for360 #992](https://github.com/madgraph5/madgraph4gpu/pull/992) into master
> 

This I will merge in 10 minutes. Just to be extra sure I will let the CI complete, should all be green. Then I will merge.

**Comment by valassi** [comment]
Ok all CI tests have passed. Merging 

Thanks again Olivier... we did it :-)

**Pull request merged**
