### PR TITLE
Fix issues in the new CI (tput_test was not executed)

### PR DESCRIPTION
**Pull request by valassi**
WIP investigate CI issues #937

### CODE REVIEW

**Comment by valassi** [comment]
Hi @oliviermattelaer can you please review? This should be totally non controversial, just fixing the new CI where one test was not running (and also fixing the printout in the CI)

Thanks Andrea

PS The usual 6 tests failing

**Comment by oliviermattelaer** [comment]
No time to look at it. But no objection to merge it if it is only fixing tests. I trust your judgment

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by valassi** [comment]
> No time to look at it. But no objection to merge it if it is only fixing tests. I trust your judgment

Thanks Olivier :-)

Very good, I will merge this shortly, so we have one less to keep track of. (Hopefully it will not expose more issues in the other PRs, but who knows, that's the whole point)

**Comment by valassi** [comment]
Merging now

**Pull request merged**
