### PR TITLE
Val june24 fixed ci

### PR DESCRIPTION
**Pull request by oliviermattelaer**
This is in order to have the full diff when combining andrea version of june24 with the proper ci.

### CODE REVIEW

**Comment by oliviermattelaer** [comment]
@andrea, we can decide what to do with this PR/branch
I do not like that much the ordering of those merge here, but the point is mainly to have a branch where everything is clean and that allow to serve as a base to move forward on your change with nb_warp_used. 

But this include the CI (his fixed) and "your" version of june24.
This link to the (upstream) gpucpp_june24 branch since that branch has actually both the change needed for master_june24 and the change for the fixing of the ci. which therefore fix issue #886

So now I'm finally in business to work on warp_used part.

**Comment by valassi** [comment]
Hi @oliviermattelaer I have fixed instead my june24 branch in #882.

I would propose to close this #981 and focus instead on #882. Tomorrow morning after I have run some tests we should be able to merge that.

Can I close this?
Thanks
Andrea

**Review by valassi — CHANGES_REQUESTED** [review]
I propose to close this and focus on #882

**Comment by valassi** [comment]
Hi @oliviermattelaer as discussed: this is a duplicate of #882 (and it is not up to date), so I am closing this.

I am about to merge #882 into master_june24 instead, and will then merge master_june24 into master in #985.

CLOSING.

**Pull request closed without merging**
