### PR TITLE
remove gXXX.cu symlinks (build XXX_cu.o from XXX.cc)

### PR DESCRIPTION
**Pull request by valassi**
Hi @roiser @oliviermattelaer I would eventually go in this direction, is this ok for you?
(I would only keep the names check.exe and gcheck.exe for now, this is the only one starting with g... it is easier to find to run).
Thanks Andrea

### CODE REVIEW

**Comment by valassi** [comment]
Hi @hageboeck @roiser as discussed this morning, this is a very simple MR that removes g*.cu symlinks and builds instead xxx_cu.o directly from xxx.c

The only exception (for now?) of a gxxx file is the gcheck.exe executable (built from check_sa_cu.o).

Any feedback? Thanks

**Comment by roiser** [comment]
Thanks @valassi I think its a good move and @hageboeck would probably integrate this into his ongoing work for the Makefiles

**Comment by valassi** [comment]
I have just merged https://github.com/madgraph5/madgraph4gpu/pull/706, I will modify this PR to merge in the new master

**Comment by valassi** [comment]
Hi @oliviermattelaer this other PR is also ready for merging.

This simplifies generated code (by removing gXXX.cu symlinks to XXX.cc files) and simplifies makefiles (by only foreseeing the build of cuda from .cc files using "-x cu", rather than relying on a .cu suffix: previously both of these were supported for different files).

The main change is this one https://github.com/madgraph5/madgraph4gpu/pull/368/commits/7b8ed4d56c2cb214ffbf460f59d398c7654c386d

Can you please @oliviermattelaer review and approve for merging?
Thanks
Andrea

**Review by oliviermattelaer — APPROVED** [review]
Sounds a nice move indeed.

Thanks,

**Comment by valassi** [comment]
Thanks @oliviermattelaer . Merging... one PR less to go.

**Pull request merged**
