### PR TITLE
Use non-zero t-channel widths in fortran as in cudacpp (recover the same physics precision in fortran and cudacpp to 10+ digits)

### PR DESCRIPTION
**Pull request by valassi**
This is a PR for issue #476, the ~permille differences between fortran and cudacpp MEs for ggtt* processes.

I intially thought this was a QCD related problem, such as alphas related. Instead it is due to the handling of the top quark width:
- fortran MEs use a top quark width hardcoded to ZERO
- cudacpp MEs use a non-zero top-quark width

The analysis is still WIP. But we also need to understand how to handle this...

@oliviermattelaer do you have a suggestion? Is there a switch in code generation to treat the top quark as width-0? Thanks

### CODE REVIEW

**Comment by valassi** [comment]
Thanks to the fix suggested by @oliviermattelaer now I run also the fortran with a zero top quark width, and the agreement betweem fortran and cudacpp cross sections is 10+ digits also for ggtt*... this is a milestone! :-)

I will self merge when all tests pass.

**Comment by oliviermattelaer** [comment]
> Thanks to the fix suggested by @oliviermattelaer now I run also the fortran with a zero top quark width, and the agreement betweem fortran and cudacpp cross sections is 10+ digits also for ggtt*... this is a milestone! :-)
> 
> I will self merge when all tests pass.

You mean non zero width in fortran right?

**Comment by valassi** [comment]
> > Thanks to the fix suggested by @oliviermattelaer now I run also the fortran with a zero top quark width, and the agreement betweem fortran and cudacpp cross sections is 10+ digits also for ggtt*... this is a milestone! :-)
> > I will self merge when all tests pass.
> 
> You mean non zero width in fortran right?

Yes sorry, NON zero also in fortran!

See this diff for instance, was ZERO, now WT

https://github.com/madgraph5/madgraph4gpu/pull/490/commits/0eb21e53e7f56b359f6d2cd760c8ff57ccfb105e

**Comment by valassi** [comment]
For the record, this is a followup to the previous PR https://github.com/madgraph5/madgraph4gpu/pull/489, continuining on fortran vs cudacpp comparisons.

Amongst the things that remain to be done before a first milestone (xsections ok, and events ~okish except for random color and helicity) there is mainly this one:

-    compare events.lhe fortran vs cudacpp (so far only checked numbers of events)... this comparison will give differences until we fix the random choice of colors and helicities (https://github.com/madgraph5/madgraph4gpu/issues/402 https://github.com/madgraph5/madgraph4gpu/issues/403
https://github.com/madgraph5/madgraph4gpu/issues/404), but all the rest should already be the same

**Pull request merged**
