### PR TITLE
Fix clang16 and clang17 builds

### PR DESCRIPTION
**Pull request by valassi**
Hi @oliviermattelaer these are small fixes for clang16 builds, can you have a look please? Thanks Andrea

### CODE REVIEW

**Comment by valassi** [comment]
This closes #904

**Comment by valassi** [comment]
In the meantime I also included similar fixes, and some wrappers, for clang16

**Comment by valassi** [comment]
And I improved the fix, adding -fPIC to fortran compilation instead of -no-pie to clang linking.

One word of motivation:
- I am doing this clang stuff to try an duse address sanitizer (with limited success)
- And I want that to debug the segfault #903 when dulicating a test
- Which in turn I want to implement #896 (adding tests for the channelid functionality)
- Which is part of my work on master_june24...

**Review by oliviermattelaer — COMMENTED** [review]
Here I'm confused...

I guess I will need to check #908 for the final code... So I put this in hold for the moment.

What confuse me is that you seems to want to fully forbid OpenMP for clang16 and clant17?  But will check in #908

**Comment by oliviermattelaer** [comment]
Hi Andrea, 

Back on this one, given that #900 is merged and that our default is no openmp, would it not make more sense to simply let the code to crash (or refuse to compile) if the user ask for openmp with such compiler?

I guess that you face issue when compiling with such compiler or was it just to simplify some test?

Cheers,

Olivier

**Comment by valassi** [comment]
Hi @oliviermattelaer thanks!

True OpenMP is now disabled by default, but one can always reenable it.

Here what I wanted to makerk is that we know that we have not ported the openmp stuff to clang, we (well I) did not find a way to make it work. If you prefer I can replace the
```
else ifneq ($(shell $(CXX) --version | egrep '^clang version 16'),)
    override OMPFLAGS = # disable OpenMP on clang16 #904
else ifneq ($(shell $(CXX) --version | egrep '^clang version 17'),)
    override OMPFLAGS = # disable OpenMP on clang17 #904
```

by something like
```
else ifneq ($(shell $(CXX) --version | egrep '^clang version 16'),)
$(error OpenMP is not supported by cudacpp on clang16 (#904))
else ifneq ($(shell $(CXX) --version | egrep '^clang version 17'),)
$(error OpenMP is not supported by cudacpp on clang17 (#904))
```

Would that be better? This was impossible when OpenMP was the default, but now that it is disabled by default, this can be a way to signal that it is not supported.

In any case I would definitely do something to signal that this was tested and found problematic. There's so many use cases and combinations, that I think it is important to makrk in the code what we are able to do and what we are not able to do.

**Comment by oliviermattelaer** [comment]
Yes, I like it :-)
As soon as you have done it, this is good to go.

Thanks,

Olivier

**Comment by valassi** [comment]
The CI is showing
163 successful, 3 in progress, and 3 failing checks 
This is expected to end with the usual 6 failures (what is pending is pp_tt012j, which is expected to fail.

Merging now.

**Pull request merged**
